[keyboard]
bindings = [
{ key = "Space", mods = "Control", action = "ToggleViMode" },
]


[font]
size = 15

[font.normal]
family = "JetBrains Mono NF"

[window]
decorations = "none"

[window.padding]
x = 5
y = 5

[general]
# import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]
import = ["~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]
