#import = ["~/.config/alacritty/themes/themes/doom_one.toml"]
#import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]
#import = ["~/.config/alacritty/themes/themes/monokai_pro.toml"]
# import = ["~/.config/alacritty/themes/themes/onenord.toml"]
import = ["~/.config/alacritty/themes/themes/catppuccin_latte.toml"]

[font]
size = 15

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "Full"

[window.padding]
x = 5
y = 5
