
[font]
size = 15

[font.normal]
family = "JetBrains Mono NF"

[window]
decorations = "none"

[window.padding]
x = 5
y = 5

[general]
#import = ["~/.config/alacritty/themes/themes/doom_one.toml"]
#import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]
#import = ["~/.config/alacritty/themes/themes/monokai_pro.toml"]
# import = ["~/.config/alacritty/themes/themes/onenord.toml"]
import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]
